title: Ksenija Kovalenka
logo: /assets/img/face.jpg
email: ksenija.kovalenka11@gmail.com
description: Physics Master's student at the University of Manchester
favicon: true
color-scheme: dark

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/KsenijaKovalenka
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: linkedin.com/in/ksenija-kovalenka

navigation:
  - name: Main
    link: ./index.html
    sublist:
      - name: Python
        link: ./index.html#python-projects
  - name: Another Page
    link: ./another-page.html
