title: Ksenija Kovalenka
logo: /assets/img/face.jpg
email: ksenija.kovalenka11@gmail.com
description: Physics PhD student at the University of Manchester
favicon: true
color-scheme: dark

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: CV
    icon: <i class="fa-regular fa-file"></i>
    link: /files/CV_latest.pdf
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/KsenijaKovalenka
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: linkedin.com/in/ksenija-kovalenka
  - name: Teaching Profile
    icon: <i class="fa-solid fa-graduation-cap"></i>
    link: https://www.mytutor.co.uk/tutors/418882/
  - name: My Art
    icon: <i class="fa-brands fa-instagram"></i>
    link: https://www.instagram.com/nesi.redenwar/
    

navigation:
  - name: Main
    link: ./index.html
    
    sublist:
      - name: C++
        link: ./index.html#quantum-circuit-simulator
      - name: Python
        link: ./index.html#python-projects
      - name: Laboratory
        link: ./index.html#selected-laboratory-projects
        
  - name: QNN
    link: ./qnn-page.html
